---

- name: Fetch Key
  apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8

- name: Adding Repository
  apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic main
    state: present

- name: Installing mysql
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: latest


#change down as well
- name: Create root user and password for mysql
  mysql_user:
    name: root
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
    encrypted: yes
    priv: '*.*:ALL'
    state: present

- name: Create wp user and password for mysql
  mysql_user:
    name: "{{ site_id }}"
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
    encrypted: yes
    priv: '*.*:ALL'
    state: present
