---

- name: Fetch Key
  apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8
  tags: mysql

- name: Adding Repository
  apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic main
    state: present
  tags: mysql

- name: Installing mysql
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present
  register: package_install
  tags: mysql

- name: Installing Python mysqlclient package
  pip: name=mysqlclient state=latest
  tags: mysql

#change down as well
- name: Generate MySQL Root Password
  set_fact: mysql_password="{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
  when: package_install.changed == True
  tags: mysql

- debug: msg={{mysql_password}}
  when: package_install.changed == True
  tags: mysql

- name: Registering mysql password for {{site_id}}
  template:
    src: ../templates/mysql/my.cnf
    dest: /root/.my.cnf
  when: package_install.changed == True
  tags: mysql

- name: Create root user and password for mysql
  mysql_user:
    name: root
    password: "{{mysql_password}}"
    priv: '*.*:ALL'
    state: present
  when: package_install.changed == True
  tags: mysql
