---
- name: Welcome to AutomateWP setup
  hosts: AutomateWP
  gather_facts: no
  pre_tasks:
    - name: Installing python3-simplejson for Ansible, Hold on...
      raw: apt-get update && apt-get -y install python3-simplejson
    - name: Gathering Facts
      setup:

  roles:
    - bootstrap
#    - security
#    - reboot
    - stack
#    - user
    - website
#    - print
