---

- name: Installing WPCLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755

- name: Downloading WordPress
  become: yes
  become_user: www-data
  shell: wp core download

- name: Fetch random salts for WordPress config
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    method: GET
    return_content: yes
  register: "wp_salt"

- include: roles/website/tasks/mysql.yml
