---
# Setup Database
# Generating MySQL DB Name
- name: "Generating MySQl DB Name"
  shell: echo "{{ site_id | lower }}" | tr '.' '_'
  register: db_name
  tags: website_db


- name: Generate MySQL Password
  set_fact: db_password="{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
  tags: website_db

- debug: msg={{db_name}}
  tags: website_db

- debug: msg={{db_password}}
  tags: website_db

- name: Setting up Database...
  mysql_db:
    name: "{{db_name.stdout }}"
    state: present
  tags: website_db

- name: Create MySQL user and password for mysql
  mysql_user:
    name: "{{db_name.stdout}}"
    password: "{{db_password}}"
    priv: "{{db_name.stdout}}.*:ALL"
    config_file: '/root/.my.cnf'
    login_unix_socket: '/run/mysqld/mysqld.sock'
    login_host: 127.0.0.1
    host: 127.0.0.1
  tags: website_db
